spring:
  application:
    name: mypages-admin
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true # 开启文件上传
      max-file-size: 3MB # 限制文件上传大小
      max-request-size: 10MB # 单次请求上传大小
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/META-INF/resources/webjars/,classpath:/resources/,classpath:/static/,classpath:/public/
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8 # 不指定会默认系统时区

# 错误页面路径
server:
  error:
    path: /sys/error
